### ISSUE TITLE
Integration not start

### ISSUE THREAD

**Issue by robyevolution** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#145]
hello there are a solution?

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant.config_entries
Source: custom_components/skyq/__init__.py:159
Integration: Sky Q (documentation, issues)
First occurred: 08:48:23 (5 occurrences)
Last logged: 09:01:40

Error setting up entry SkyQ Camera for skyq
Error setting up entry SkyQ Salone for skyq
Error setting up entry Sky Q Salone for skyq
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.homeassistant/custom_components/skyq/__init__.py", line 64, in async_setup_entry
    _check_for_storage_contents(hass)
  File "/home/homeassistant/.homeassistant/custom_components/skyq/__init__.py", line 159, in _check_for_storage_contents
    file_content = json.load(infile)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by RogerSelwyn** [comment]
Delete config/.storage/skyq .restore_state and restart

**Comment by robyevolution** [comment]
works thanks!

**Comment by RogerSelwyn** [comment]
The code should now correctly handle this error to avoid manual action being required - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.10.13
