### ISSUE TITLE
[BUG] Media Browser not working - Unknown error

### ISSUE THREAD

**Issue by TheBisk** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#147]
I noticed that the media browser no longer works, both from a PC and from a smartphone. I use chrome browser and the latest version of HA 2023.5.3

**Component versions**  
1. What version of SkyQ component are you using? **v2.10.13**
2. What was the last version where the problem was not shown? **don't know**

**Your configuration**  
How have you setup your devices, by UI or YAML? **UI**

**Output of HA logs**  
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/skyq/classes/mediabrowser.py:85
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 16:43:04 (4 occurrences)
Last logged: 16:45:03

[547150582336] Error handling message: Unknown error (unknown_error) xxx from xx.xx.xxx.xx (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1223, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/skyq/media_player.py", line 502, in async_browse_media
    return await self._media_browser.async_browse_media(
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 31, in async_browse_media
    channellist = await self._async_prepare_channels(hass, channel_list)
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 58, in _async_prepare_channels
    channel = await self._async_get_channel_info(hass, channel_list, source)
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 85, in _async_get_channel_info
    programme = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyskyqremote/skyq_remote.py", line 161, in get_programme_from_epg
    programme = next(
  File "/usr/local/lib/python3.10/site-packages/pyskyqremote/skyq_remote.py", line 164, in <genexpr>
    if p.starttime <= query_date and p.endtime >= query_date
TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by RogerSelwyn** [comment]
Should be fixed with the release in pre-release - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.10.14

**Comment by TheBisk** [comment]
I do confirm. Its working again. Thanks.
