### ISSUE TITLE
integration problem

### ISSUE THREAD

**Issue by robyevolution** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#16]
hello I have problems with the integration, I installed the latest version through hacs, I have the latest version of home assistant but I am not part of this integration
this is the error log:

2020-07-19 21:03:21 ERROR (MainThread) [homeassistant.config] Platform error: media_player
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/config.py", line 780, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 321, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/skyq/__init__.py", line 4, in <module>
    from pyskyqremote.skyq_remote import SkyQRemote
ModuleNotFoundError: No module named 'pyskyqremote'

**Comment by RogerSelwyn** [comment]
Sounds like you need to restart has because pyskyqremote would be installed at reboot

**Comment by robyevolution** [comment]
Resolved!
I thought it was installed automatically.
