### ISSUE TITLE
Error on 0.115.5

### ISSUE THREAD

**Issue by monkeypr00f** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#28]
Can't access to integration option pannel anymore since upgrade.
This is the system log:

```
Logger: aiohttp.server
Source: data_entry_flow.py:204
First occurred: 10:49:57 (1 occurrences)
Last logged: 10:49:57

Error handling request
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/skyq/config_flow.py", line 153, in async_step_init
    c for c in self._channel_list if c.channelname == channel
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/config/config_entries.py", line 210, in post
    return await super().post(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/data_entry_flow.py", line 73, in post
    "show_advanced_options": data["show_advanced_options"],
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 132, in async_init
    flow, flow.init_step, data, init_done
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 204, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
RuntimeError: coroutine raised StopIteration
```

**Comment by monkeypr00f** [comment]
already tried upgrade/reinstall the integration

**Comment by RogerSelwyn** [comment]
I suspect this is not to do with any upgrade, but to do with a change in channel line up. I'll try and get a fix out for what I think it is.

From your list of channels that you've selected previously in options, do you know if any of those channels have been removed/changed name by Sky?

**Comment by monkeypr00f** [comment]
There was since 2 days ago a custom name for Fox+1. They changed it, but the channel never worked with the different name.
I removed the generated switch yaml form main config, restarted, but it throws the same error.

**Comment by RogerSelwyn** [comment]
Try this new version - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.4.3

**Comment by monkeypr00f** [comment]
Now it works! Thanks mate!
