### ISSUE TITLE
[BUG] - Error adding SkyQ Mini

### ISSUE THREAD

**Issue by claudiosala80** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#34]
**Describe the bug**  
I have now also SkyQ Mini (ITA), but I cannot add

**To Reproduce**  
1. Adding new SkyQ mini decoder
4. ITA

**Expected behavior**  
Able to add

**Screenshots**  

**Component versions**  

**Your configuration**  
UI, but also with YAML there is the same issue

**Output of HA logs**  
2020-10-25 17:39:33 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/config/config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 156, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 204, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/home/homeassistant/.homeassistant/custom_components/skyq/config_flow.py", line 75, in async_step_user
    await self._async_setUniqueID(host)
  File "/home/homeassistant/.homeassistant/custom_components/skyq/config_flow.py", line 88, in _async_setUniqueID
    remote = await self.hass.async_add_executor_job(SkyQRemote, host)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/pyskyqremote/skyq_remote.py", line 97, in __init__
    deviceInfo = self.getDeviceInformation()
  File "/srv/homeassistant/lib/python3.7/site-packages/pyskyqremote/skyq_remote.py", line 349, in getDeviceInformation
    hardwareModel = systemInfo["hardwareModel"]
KeyError: 'hardwareModel'

**Comment by RogerSelwyn** [comment]
Please run this command against your IP - http://192.168.1.20:9006/as/system/deviceinformation

**Comment by claudiosala80** [comment]
Upgrade of the firmware solved the issue.
Apologize me
