### ISSUE TITLE
[BUG] Device becomes duplicated at night

### ISSUE THREAD

**Issue by RogerSelwyn** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#53]
Reported by Kata - https://community.home-assistant.io/t/custom-component-skyq-media-player/140306/739
**Describe the bug**  
My device becomes unavailable at night (because of stand by i suppose), but it remains no longer available unless i restart ha (it happens every morning)…
What am i missing?

**To Reproduce**  
1. Overnight running

**Expected behavior**  
All HASS instances should be running

**Screenshots**  

**Component versions**  
1. Latest
2. n/a

**Your configuration**  
YAML.

**Your configuration from the options dialogue**  
or  
**Your configuration.yaml**  
```yaml
platform: skyq
name: ‘SkyQ Platinum’
host: 192.168.1.100
room: ‘Soggiorno’
live_tv: True

platform: skyq
name: ‘SkyQ Mini Camera’
host: 192.168.1.102
room: ‘Camera’
live_tv: True

platform: skyq
name: ‘SkyQ Mini Taverna’
host: 192.168.1.101
room: ‘Taverna’
live_tv: True
````
**Output of HA logs**  

This is what i found in the log :

```
Logger: custom_components.skyq.media_player
Source: custom_components/skyq/media_player.py:185 
Integration: Sky Q (documentation, issues) 
First occurred: 3:00:57 (3 occurrences) 
Last logged: 3:00:57

W0010M - Device is not available: SkyQ Mini Taverna
W0010M - Device is not available: SkyQ Platinum
W0010M - Device is not available: SkyQ Mini Camera
```

Then, at 5.00 :

```
Logger: homeassistant.helpers.entity
Source: custom_components/skyq/media_player.py:447 
First occurred: 5:01:42 (2 occurrences) 
Last logged: 5:02:32

Update for media_player.skyq_mini_taverna_2 fails
Update for media_player.skyq_mini_camera_2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 292, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 490, in async_device_update
    raise exc
  File "/config/custom_components/skyq/media_player.py", line 353, in async_update
    await self._async_updateState()
  File "/config/custom_components/skyq/media_player.py", line 447, in _async_updateState
    powerState = await self.hass.async_add_executor_job(self._remote.powerStatus)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyskyqremote/skyq_remote.py", line 92, in powerStatus
    self._setupRemote()
  File "/usr/local/lib/python3.8/site-packages/pyskyqremote/skyq_remote.py", line 486, in _setupRemote
    self._channels = self._getChannels()
  File "/usr/local/lib/python3.8/site-packages/pyskyqremote/skyq_remote.py", line 466, in _getChannels
    return channels["services"]
KeyError: 'services'
```

immediately followed by

```
Logger: custom_components.skyq.media_player
Source: custom_components/skyq/media_player.py:586 
Integration: Sky Q (documentation, issues) 
First occurred: 5:02:22 (3 occurrences) 
Last logged: 5:02:42

W0020M - Device is now available: SkyQ Mini Taverna
W0020M - Device is now available: SkyQ Platinum
W0020M - Device is now available: SkyQ Mini Camera
```

**Additional context**  
![eb2c4f952e7b5e7605b7cca78f3eae5c2571e10c_2_1380x522](https://user-images.githubusercontent.com/7115783/115205190-344dab80-a0f1-11eb-8d90-d2c1df9ec8b3.png)

**Comment by RogerSelwyn** [comment]
Ok, it worked!
It seems that devices are not duplicated, with UI setup.
This morning i found the same entities, all of them available.
This is the log (3AM):


```
Logger: custom_components.skyq.media_player
Source: custom_components/skyq/media_player.py:185 
Integration: Sky Q (documentation, issues) 
First occurred: 3:00:57 (3 occurrences) 
Last logged: 3:00:57

W0010M - Device is not available: Sky Q - Mini Taverna
W0010M - Device is not available: Sky Q - Mini Camera
W0010M - Device is not available: Sky Q - Platinum
```

then (5AM)


```
Logger: homeassistant.helpers.entity
Source: custom_components/skyq/media_player.py:447 
First occurred: 5:02:15 (2 occurrences) 
Last logged: 5:02:22

Update for media_player.sky_q_mini_taverna fails
Update for media_player.sky_q_mini_camera fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 292, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 490, in async_device_update
    raise exc
  File "/config/custom_components/skyq/media_player.py", line 353, in async_update
    await self._async_updateState()
  File "/config/custom_components/skyq/media_player.py", line 447, in _async_updateState
    powerState = await self.hass.async_add_executor_job(self._remote.powerStatus)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyskyqremote/skyq_remote.py", line 92, in powerStatus
    self._setupRemote()
  File "/usr/local/lib/python3.8/site-packages/pyskyqremote/skyq_remote.py", line 486, in _setupRemote
    self._channels = self._getChannels()
  File "/usr/local/lib/python3.8/site-packages/pyskyqremote/skyq_remote.py", line 466, in _getChannels
    return channels["services"]
KeyError: 'services'
```

followed by
```

Logger: custom_components.skyq.media_player
Source: custom_components/skyq/media_player.py:586 
Integration: Sky Q (documentation, issues) 
First occurred: 5:02:21 (3 occurrences) 
Last logged: 5:02:34

W0020M - Device is now available: Sky Q - Mini Taverna
W0020M - Device is now available: Sky Q - Mini Camera
W0020M - Device is now available: Sky Q - Platinum
```

The ‘id codes’ are different (w0010m - w0020M) but there are no ‘duplicates’ and they are available, both in the UI and in the status page.

**Comment by RogerSelwyn** [comment]
Do you reboot your HASS instance overnight at 3am by any chance? The only way you should get W0010M (and then W0020M) is at HASS startup.

**Comment by KataGit** [comment]
> Do you reboot your HASS instance overnight at 3am by any chance? The only way you should get W0010M (and then W0020M) is at HASS startup.

Yes!
I forgot there was an automation for rebooting, exactly at 3AM.
Do i need to disable it?

**Comment by RogerSelwyn** [comment]
> Yes!
> I forgot it, but there is an automation for rebooting, exactly at 3AM.
> Now it's disabled.

Well I'm working a solution for the error you were getting in the logs, so it handles unavailable devices better. Can't get a full resolution for YAML based. I expect there is a way, but I can't figure it out. So just take the next update, and those errors should go, or schedule the reboot for earlier (UK sleep times are 2.45-5.45).

**Comment by KataGit** [comment]
Ok! 
Thanks a lot for the help....

For the moment, i'm not interested in resuming the reboot, so i'll leave the situation as it is.

**Comment by RogerSelwyn** [comment]
Fixed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.5.9
