### ISSUE TITLE
[BUG] Media Browser not working - Error handling message: Unknown error

### ISSUE THREAD

**Issue by TheBisk** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#78]
**Describe the bug**  
 Media Player Browser not working: **Unknown error**

Version 2.7.5. 
H.A. 2012.12.1

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/skyq/classes/mediabrowser.py:68
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:36:28 (6 occurrences)
Last logged: 12:46:12

[548030696608] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1168, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/skyq/media_player.py", line 424, in async_browse_media
    return await self._media_browser.async_browse_media(
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 28, in async_browse_media
    channellist = await self._async_prepareChannels(hass, channel_list)
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 55, in _async_prepareChannels
    channel = await self._async_get_channelInfo(hass, channel_list, source)
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 68, in _async_get_channelInfo
    channelInfo = await hass.async_add_executor_job(self._remote.getChannelInfo, channelno)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyskyqremote/skyq_remote.py", line 293, in getChannelInfo
    return self._channelInformation.getChannelInfo(channelNo)
  File "/usr/local/lib/python3.9/site-packages/pyskyqremote/classes/channel.py", line 55, in getChannelInfo
    channelImageUrl = self._remoteCountry.buildChannelImageUrl(channelsid, channelname)
AttributeError: 'NoneType' object has no attribute 'buildChannelImageUrl'

**Comment by RogerSelwyn** [comment]
Please provide details of your configuration including what version you are on, and what version previously worked.

**Comment by RogerSelwyn** [comment]
Want I need to know for this is what channels you have configured in both Sundays and custom sources and what version you are on. Also whether you are the uk or not.

**Comment by RogerSelwyn** [comment]
I've posted an update to pyskyqremote. If you modify manifest.json to point to 0.2.53 that should fix the issue. I'll post a new SkyQ remote tomorrow.

**Comment by TheBisk** [comment]
I edited the manifest.json to point 0.2.53, saved and restarted home assistant.  Media browser now is working fine as before. Issue is fixed, Thank you.
