### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by ik0adr** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#94]
**Describe the bug**  
After adding a channel, clicking on the 'browse multimedia' icon gives a "unknown error" page.
**To Reproduce**  
1. What were you doing/watching at the time ? 
2. What channel were you on?
3. What time did the problem occur? unkown error
4. Where are you (bear in mind component supports GBR/ITA at the moment)? ITA

**Expected behavior**  

**Screenshots**  

**Component versions**  
1. What version of SkyQ component are you using?
2.8.4
2. What was the last version where the problem was not shown?
don't know
**Your configuration**  
How have you setup your devices, by UI or YAML?
UI
**Your configuration from the options dialogue**  
or  
**Your configuration.yaml**  
```yaml
media_player:
 - platform:  skyq
   name: SkyQ Living Room
   host: 192.168.0.10
   live_tv: True
   country: "UK"
   sources:
      SkyOne: '1,0,6'
      SkyNews: '5,0,1'
````
**Output of HA logs**  
Paste the relavant output of the HA log here.
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/skyq/classes/mediabrowser.py:98
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 19:49:48 (2 occurrences)
Last logged: 19:51:29

[2738497832] Error handling message: Unknown error
[2756019512] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1162, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/skyq/media_player.py", line 465, in async_browse_media
    return await self._media_browser.async_browse_media(
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 35, in async_browse_media
    channellist = await self._async_prepare_channels(hass, channel_list)
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 62, in _async_prepare_channels
    channel = await self._async_get_channel_info(hass, channel_list, source)
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 98, in _async_get_channel_info
    "thumbnail": self._app_image_url.getAppImageUrl(source),
AttributeError: 'AppImageUrl' object has no attribute 'getAppImageUrl'
**Additional context**

**Comment by RogerSelwyn** [comment]
I probably know what your problem is, but assuming you have a UK box, you don’t need the UK in your configuration, it will find that from your box. I’ll have a look tomorrow, because that may or may not be the problem, but I made some changes in that area in the latest release.

**Comment by RogerSelwyn** [comment]
It would help if you can tell me what channel you were watching at the time. I can see what time it was. Or does it do this on any channel?

**Comment by RogerSelwyn** [comment]
Fixed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.8.5
