### ISSUE TITLE
[BUG] UsedStorage sensor not working - Error adding entities for domain sensor with platform skyq

### ISSUE THREAD

**Issue by B-Hartley** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#96]
**Describe the bug**  
Used storage sensor not working.

Error adding entities for domain sensor with platform skyq

**To Reproduce**  
start home assistant on 2022.04.b

**Expected behavior**  
No errors in log.

**Screenshots**  

**Component versions**  
1. What version of SkyQ component are you using? v2.8.7
2. What was the last version where the problem was not shown? problem came about due to core 2022.04.b03 (or probably b0)

**Your configuration**  
UI

**Your configuration from the options dialogue**  
or  
**Your configuration.yaml**  

**Output of HA logs**  
```
2022-04-02 17:29:11 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform skyq
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
2022-04-02 17:29:12 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up skyq platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```

**Additional context**

**Comment by RogerSelwyn** [comment]
Ok, I’ll look at it in a week’s time when I get home

**Comment by B-Hartley** [comment]
thanks.

**Comment by RogerSelwyn** [comment]
To be honest I find that error strange because that storage sensor is set to a category using a constant imported from HA core. So I don't really understand why it is invalid. It would need tracking back as to what list they are validating against.

**Comment by RogerSelwyn** [comment]
Looks like they have changed it from a constant to a class. (This is notes for myself).

**Comment by RogerSelwyn** [comment]
Fixed with v2.8.8 - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.8.8

**Comment by RogerSelwyn** [comment]
Had some time, so did the fix.

**Comment by B-Hartley** [comment]
Thanks !
